### ISSUE TITLE
Unusual avgDuration numbers

### ISSUE THREAD

**Issue by BillPetti** [VisitData-org/ca_visit_tracking#169]
I am assuming the `avgDuration` variable is in minutes. If so, there are some interesting outliers, such as Grocer Stores on 2020-04-11 in South Carolina (`avgDuration` == 8401 minutes) and cosmetic shops in Louisianna on 2020-02-27 (`avgDuration` == 8506 minutes).

See attached for all those that appear to be over 4 hours. Most of these make sense (or, could make sense), but some definitely seemed odd.

[fsqr_duration_outliers.xlsx](https://github.com/VisitData-org/ca_visit_tracking/files/4565968/fsqr_duration_outliers.xlsx)

**Comment by ajanian** [comment]
That's why we are using median.  In most of these scenarios the issue was someone working at the store.  i.e. they were they were most people at the gas station for 3 minutes filling their tank and then others that were there for 9 hours working.  Certainly 141 hours average doesn't make sense for the cosmetic shop unless someone is living there as well and they have been there since they started staying at home.  :-)

**Comment by dsjoerg** [comment]
We are going to eliminate the `avgDuration` variable from the data because of issues like this.

**Comment by dsjoerg** [comment]
Thank you for bringing up the issue.   https://github.com/VisitData-org/ca_visit_tracking/issues/164 is the work for eliminating it. Will make that more explicit.

**Comment by BillPetti** [comment]
I figured it was something like that. So `p50Duration` is effectively 50th percentile/median. Makes sense.

Is there a data dictionary for the raw data? 

Thanks again for making this data available.

**Comment by dsjoerg** [comment]
We are starting some documentation here: https://docs.google.com/document/d/15Y2FKl91449hV4aWwG4lt_LLOkbsjhcAqLZ3SNy_X1k/edit# it's a work in progress.
