### ISSUE TITLE
Only show last 7 days on mobile?

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#36]

**Comment by ajanian** [comment]
I don't love that.  I feel like it really impacts the usability, no?  we must be doing something wrong because there are plenty of charts that we all use that go longer than 7 days and can still see things.  Yahoo finance on my iphone, for example.  I'm not saying I know how to fix it but I think it can be fixed

**Comment by robertobuso** [comment]
This is an example of how a 20+ day chart currently looks in mobile (Beaches in LA):
<img width="797" alt="Screen Shot 2020-03-29 at 8 40 46 PM" src="https://user-images.githubusercontent.com/38298182/77865728-d60c0d00-71fd-11ea-941b-b6f502489055.png">

**Comment by dsjoerg** [comment]
I will post a comparison / mockup and then we can discuss with more clarity. Ball's in my court.

**Comment by ajanian** [comment]
98.5% of our traffic is from desktop so I think we should close this.  We have to take a full look at mobile if we really want to make it a first class experience.
