### ISSUE TITLE
Show top venue per county/venuetype

### ISSUE THREAD

**Issue by dsjoerg** [VisitData-org/ca_visit_tracking#88]
To help people verify correctness of the data who are skeptical.

https://drive.google.com/file/d/1TJQR8UcC5mpP9BQfnZxOfJD1G_Pl6F6h

Step 1: propose some UX for how to expose this information

**Comment by ajanian** [comment]
Here are some ideas:
- because it is only 3 items and it is by date, when you hover over a date in the chart it could show you in the tooltip.  that would work nicely on desktop I think.
- same on the hover in the table down below.  when we have this data for something we could make one of the fields a link and open a little window when someone clicks it.
- when looking at a county / location type it could show you another table with the last N days and the top places in a unique table.

**Comment by ajanian** [comment]
we decided this was a potential problem for privacy so we reverted the change
